### ISSUE TITLE
Resource type editfile doesn't exist

### ISSUE THREAD

**Issue by ltutar** [pulling-strings/puppet-gitblit#1]
I was using this module to install gitblit. I am not sure if it is still maintained. 
I get the following error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Virtual Query, Resource type editfile doesn't exist at /etc/puppetlabs/code/environments/production/modules/gitblit/manifests/config.pp:14:47 on node puppetagent1.home

Downloading editfile from https://github.com/mstrauss/puppet-editfile solved this problem. Maybe you can edit the dependencies information.

**Comment by narkisr** [comment]
This module is used in conjuection with this  [opskeleton](http://opskeleton.github.io/opskeleton/latest/)  [project](https://github.com/opskeleton/gitblit-sandbox), 

The depdencies are stated [here](https://github.com/opskeleton/gitblit-sandbox/blob/master/Puppetfile)

I usually don't bother with puppet-forge since I use git for the source of my modules,I'm still considering to add some of them to the forge so I can update the metadata.json
